### ISSUE TITLE
halfnarp track

### ISSUE THREAD

**Issue by bread-on-toast** [ligi/Confi#1]
Hi,
I think one track(could be shown as a separate Room) where one's marked sessions are shown would be a nice feature.

**Comment by johnjohndoe** [comment]
Scribble, sketch please.. so it is easier to discuss. Please note there are favorites already.

**Comment by ligi** [comment]
I think he means "favs as track" - I had something like this in mind anyway - thanks for the feedback

**Comment by johnjohndoe** [comment]
Does this mean this virtual favorites "room" aka. track would show all events in parallel to the full schedule? One needs to think about simultaneous or overlapping events.

**Comment by ligi** [comment]
I think a row should be a configurable data-source
