### ISSUE TITLE
Alternative/additional app

### ISSUE THREAD

**Issue by PanderMusubi** [ligi/Confi#3]
You could alternatively/additionally also offer the planning in XML to https://f-droid.org/repository/browse/?fdid=net.gaast.giggity

**Comment by ligi** [comment]
Thanks for the suggestion but I do not see this happen here

**Comment by johnjohndoe** [comment]
@PanderMusubi What do you exactly mean by "offer the planning in XML"?

**Comment by PanderMusubi** [comment]
Giggity can show the schedule, and it did so also for 33C3. For upcoming FOSDEM I had to remind the maintainer a few weeks ago but he immediately supported that too. So with "offering" I meant "notify" when the schedule is available. so there is already an open app out there offer some of the required core functionality.

**Comment by johnjohndoe** [comment]
Giggity follows the all-events-in-one-app-approach. The Confi app is more like blueprint for customized apps for specific events. I cannot imagine what the app should offer is the schedule of an event has not been released yet. It will just be empty.
